### ISSUE TITLE
TypeError: Cannot read property 'shortcode' of undefined

### ISSUE THREAD

**Issue by maxmati** [zmora-agh/zmora-ui#174]
Prawdopodobnie trzeba obsłużyć nieudana wczytywanie danych w breadcrumbs

https://sentry.io/mateusz-nowotynski/zmora-agh/issues/320681096/

```
TypeError: Cannot read property 'shortcode' of undefined
  at None (/main.aea428bbf5896419655d.js:1:73782)
  at None (/main.aea428bbf5896419655d.js:1:73447)
  at o.render (/main.aea428bbf5896419655d.js:39:94714)
  at d._renderValidatedComponentWithoutOwnerOrContext (/main.aea428bbf5896419655d.js:39:101161)
  at d._renderValidatedComponent (/main.aea428bbf5896419655d.js:39:101373)
...
(38 additional frame(s) were not displayed)
```

**Comment by marcmos** [comment]
Prawdopodobnie powiązane z #156.
