### ISSUE TITLE
Użytkownik nie jest przekierowywany do strony 404 przy nie istniejący contescie na stronie problemu

### ISSUE THREAD

**Issue by maxmati** [zmora-agh/zmora-ui#189]
https://sentry.io/mateusz-nowotynski/zmora-agh/issues/320683465/

```
TypeError: Cannot read property 'owners' of null
  at t.value (/0.f4dc4428aa24ca5bd521.chunk.js:1:36230)
  at t.value (/0.f4dc4428aa24ca5bd521.chunk.js:1:35630)
  at t.value (/0.f4dc4428aa24ca5bd521.chunk.js:1:35311)
  at c._performComponentUpdate (/main.3738267e01fe69f1e8bc.js:26:100549)
  at c.updateComponent (/main.3738267e01fe69f1e8bc.js:26:99930)
...
(36 additional frame(s) were not displayed)
```

**Comment by maxmati** [comment]
https://sentry.io/mateusz-nowotynski/zmora-agh/issues/320683445/
